version: "3"

services:
  
  python:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true

  influxdb:
    image: influxdb:2.6.1
    ports:
      - "8086:8086"
    volumes:
      - ./docker/influxdb/data:/var/lib/influxdb2
      - ./docker/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=switchbot

  grafana:
    image: grafana/grafana-oss:9.4.1
    # command: /bin/sh -c "sed -i 's/^http_port = 3000/http_port = 3001/' /etc/grafana/grafana.ini && /run.sh"
    # user: "472"
    ports:
      - "3001:3001"
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
      - ./docker/grafana/data/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb
